"""Add photo upload system

Revision ID: 50a155460b3a
Revises: 53a329335388
Create Date: 2025-08-30 22:07:11.432189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50a155460b3a'
down_revision: Union[str, Sequence[str], None] = '53a329335388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('uploaded_by', sa.Integer(), nullable=False))
    op.add_column('photos', sa.Column('notes', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'photos', 'users', ['uploaded_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.drop_column('photos', 'notes')
    op.drop_column('photos', 'uploaded_by')
    # ### end Alembic commands ###
